### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by moehreag** [Intro-Dev/Osmium#12]
I have a few things which are good and a few that maybe could be better.
Firstly, thanks for making a great Mod!

Positive things:
- many features
- nice in-game gui (even works perfectly with _Blur_)

Things to maybe improve:
- Add a scale to the Potion Display
- move the mod name in the GUI scaled based on the GUI scale (otherwise it looks not so nice)
![osmium-1](https://user-images.githubusercontent.com/85403855/130561878-59506857-e254-4cab-88c8-71892d58f134.png)
(I used other mods while taking this screenshot)
- add a button to exit the config of one specific module
- add more HUD elements (like a ping & cps display, toggleable Keystrokes, etc..)
- You could contact IsXander maybe because he looks out for somebody making his mod [_EvergreenHud_](https://github.com/isXander/EvergreenHUD/tree/kotlin-rewrite) for newer versions (I think you could team up!)

Thanks again for your active developement of this nice mod.

**Comment by Intro-Dev** [comment]
Thanks for the feedback! I'll start working on improving the HUD now, and I've already started working on more features. As for teaming up with IsXander, I'll think about it.

**Comment by moehreag** [comment]
Thanks for your fast reply!
As soon as the 'essential' features are working, would it be OK for you that I include your mod in my Modpack/client
[AxolotlClient](https://github.com/moehreag/AxolotlClient)? (I ask even though It would be permitted by your chosen license)

**Comment by Intro-Dev** [comment]
Of course! Just include some kind of credit somewhere in the modpack.

**Comment by moehreag** [comment]
👌 I always give credits to mod devs, and try to get downloads from their official source whenever possible. (Not possible for CF only mods due to their download timer)

**Comment by moehreag** [comment]
One more thing: Is the issue of directly being moved to Limbo when joining hypixel (while using your mod, without it not) already known?

**Comment by Intro-Dev** [comment]
That issue is currently known, but I have no idea what might be causing it right now. I'll try to get it fixed in the next release. In the meantime, you can just /l in limbo to play Hypixel.

**Comment by Intro-Dev** [comment]
Just fixed the bug with Hypixel.

**Comment by moehreag** [comment]
Thank you!

**Comment by moehreag** [comment]
> That issue is currently known, but I have no idea what might be causing it right now. I'll try to get it fixed in the next release. In the meantime, you can just /l in limbo to play Hypixel.

Actually, this didn't work for me, I was just sent back to limbo directly. But If it's fixed, that's great!

**Comment by Intro-Dev** [comment]
I just released 1.2.2, which implemented all these features and addressed your issues with GUI scaling. Thanks for all the feedback!

**Comment by moehreag** [comment]
Thanks! I'll test it out as soon as possible, I will bring Feedback probably tomorrow afternoon (GMT+1/Summertime so actually GMT+2)
