### ISSUE TITLE
features are already in the game

### ISSUE THREAD

**Issue by PistonUser** [Intro-Dev/Osmium#14]
togglesprint and toggle sneak are already in the default game

**Comment by Intro-Dev** [comment]
Hi! Although togglesneak is already part of the vanilla game, in vanilla it lacks any sort of display or customizability, which Osmium has.

**Comment by PistonUser** [comment]
> Hi! Although togglesneak is already part of the vanilla game, in vanilla it lacks any sort of display or customizability, which Osmium has.

OH ok :)
