### ISSUE TITLE
Bug Report: Crash when changing the "Custom Capes" setting and a bit more

### ISSUE THREAD

**Issue by moehreag** [Intro-Dev/Osmium#15]
When changing the "Custom Capes" option in the settings screen and clicking "Back" while In-Game, the game crashes ([Crash Report](https://bytebin.lucko.me/izhJMeV7cP) (uploaded with notenoughcrashes)). 
Another thing I found out is that without changing anything, Osmium even removes vanilla Capes (I recognized this especially now with the migrator capes).

 I don't think this is related to Osmium, but somehow you stay connected to a Server when this crash occurs and NEC is installed (https://github.com/natanfudge/Not-Enough-Crashes/issues/67).

Apart from that, you created a great mod, that could easily be used more.

**Comment by Intro-Dev** [comment]
This bug with capes crashing is known, and is has been fixed. As for the issue with crashing on joining servers, I don't think that Osmium can be responsible, but I will look into it.

**Comment by moehreag** [comment]
Ok, thanks! I looked for it in before, but didn't find an issue targeting this.

**Comment by Intro-Dev** [comment]
I haven't really been making issues for bugs, but I probably should.

**Comment by moehreag** [comment]
You could maybe make a template like IsXander has for their bug Reports (I think theirs is quite nice)

**Comment by Intro-Dev** [comment]
Bugs with joining servers and with cape rendering fixes as of commit 7440ad3dc65af3d1ea5ebe7e616432f2df06e082. And for issue templates I'll probably make one soon.
