### ISSUE TITLE
wehn i open osmium options it crashes the game for context i have a bunch of mods installed but idk whats causing the problem log:https://bytebin.lucko.me/ceu9992qM8

### ISSUE THREAD

**Issue by Zombiegamer3434** [Intro-Dev/Osmium#16]

**Comment by Zombiegamer3434** [comment]
ur not lambda ar u

**Comment by Intro-Dev** [comment]
No, I am not lambda. As for your issue with crashes, with so many mods, its hard to tell what is crashing, but my best guess is that Slight Gui Modifications is causing the crash.
