### ISSUE TITLE
[(FEATURE) REQUEST] Create a Discord (or any other communication platform) Server 

### ISSUE THREAD

**Issue by moehreag** [Intro-Dev/Osmium#18]
**Is your feature request related to a problem? Please describe.**
This should be clear already.

**Describe the solution you'd like**
Having a place to communicate easier with the Dev(s), and a link to it in the Readme.

**Describe alternatives you've considered**
Just communicating over github is not practical over a long time.

**Comment by Intro-Dev** [comment]
The Osmium Development discord server is open at https://discord.gg/QHne9ARYGe
