### ISSUE TITLE
[BUG] Crash when selecting Color: Index out of Bounds

### ISSUE THREAD

**Issue by moehreag** [Intro-Dev/Osmium#24]
**Describe the bug**
The Game crashes when selecting any color that contains more green than yellow or more blue than pink (I think it is)

**To Reproduce**
1. Go to the Block Overlay Settings (or any other settings page with a color picker, e.g. the keystrokes page)
2. Click on any color that follows the scheme described above
3. See error

**Expected behavior**
The color selects as when selecting any other color (e.g. red)

**Screenshots / Log Files**
Crash Report 1:
[crash-2021-09-25_17.34.55-client.txt](https://github.com/Intro-Dev/Osmium/files/7229984/crash-2021-09-25_17.34.55-client.txt)
Crash Report 2:
[crash-2021-09-25_17.44.00-client.txt](https://github.com/Intro-Dev/Osmium/files/7229987/crash-2021-09-25_17.44.00-client.txt)

**Comment by Intro-Dev** [comment]
Looks like the scale calculations for getting the color at the mouse pointer are off.

**Comment by moehreag** [comment]
> Looks like the scale calculations for getting the color at the mouse pointer are off.

yep, think this too, since somehow some kind of orange on the Picker is producing blue and green colors, and red the other way round. Another thing I could think of seeing on these settings screens is some kind of feedback which color is currently selected.
