### ISSUE TITLE
[BUG] Crash when trying to join nucleoid.xyz

### ISSUE THREAD

**Issue by moehreag** [Intro-Dev/Osmium#25]
**Describe the bug**

**To Reproduce**
1. Go to 'Multiplayer' (Add server 'nucleoid.xyz')
2. Try to join 'Nucleoid'

**Expected behavior**
The Server loads like on vanilla

**Screenshots / Log Files**
[Crash log](https://gist.githubusercontent.com/natanfudge/0764050584034e08a2d2188ecca1fd48/raw/23182cdbd5631bc7c5bd437ebe6b53ef170905a8/crash.txt)
(If more logs are needed, I have around 20 of the same error)

**Additional contexts**
Seems like this crash has something to do with the Ping Display. I for myself only can't figure out why this is.
It may also be caused by a mod running on [Nucleoid](https://github.com/NucleoidMC) (luckily everything they do is open-source)

**Comment by Intro-Dev** [comment]
Looks like that specific server is messing with player ping information. Should be an easy enough fix.
