### ISSUE TITLE
How to get custom cape

### ISSUE THREAD

**Issue by 6270** [Intro-Dev/Osmium#27]
where is the file location for capes?

**Comment by moehreag** [comment]
It is  the 'cosmetics' directory  in the folder above your game directory as stated in CosmeticManager.java, line 105: 
            File cosmeticsDir = FabricLoader.getInstance().getGameDir().getParent().resolve("cosmetics").toFile()

**Comment by Intro-Dev** [comment]
see https://github.com/Intro-Dev/Osmium/wiki/Cape-packs
