### ISSUE TITLE
Badlion/Lunar Motionblur [FEATURE REQUEST]

### ISSUE THREAD

**Issue by BuckinghamStudios** [Intro-Dev/Osmium#39]
One of my favorite mods from any pvp client is motionblur, and my game just doesnt feel as smooth without it. There is currently no motionblur fabric mod out there, so this could be the first to actually have it.

**Comment by moehreag** [comment]
Yes there is! (But not as a small mod with only that feature) I'm unsure if I'm allowed to post a link here (since it's my project).

**Comment by BuckinghamStudios** [comment]
> Yes there is! (But not as a small mod with only that feature) I'm unsure if I'm allowed to post a link here (since it's my project).

Im already in ur discord and I know, its just that it doesnt really work for me and there are a lot of bugs

**Comment by Intro-Dev** [comment]
I can get it done by next update

**Comment by venaminecraft** [comment]
Hello @hdusahd, you could try this one here: https://modrinth.com/mod/motionblur

**Comment by Intro-Dev** [comment]
Sorry for getting to this late. Unfortunately due to my lack of understanding of minecrafts shader system, I can't implement this. I suggest you do what @sternschnaube and use another mod.
