### ISSUE TITLE
[FEATURE REQUEST] Where is 1.19.2???

### ISSUE THREAD

**Issue by TheTrueBeeGuy** [Intro-Dev/Osmium#40]
**Is your feature request related to a problem? Please describe.**
Well... where is Osmium for 1.19.2? i tried downloading the 1.19 and the 1.19.3 Version, my game just doesn't start because of it

**Describe the solution you'd like**
Add a version for Osmium Fabric 1.19.2

**Describe alternatives you've considered**
Add a Osmium Mod with Compatibility to any Version from 1.19 to 1.19.3

**Additional context**
The Osmium Mod is a really cool concept, you wont need anymore to use any Client that can't have mods on, like Lunar and Badlion

**Comment by Intro-Dev** [comment]
Unfortunately there is no release 1.19.2 build, only development builds. You can download the last 1.19.2 build [here](https://github.com/Intro-Dev/Osmium/suites/9511788849/artifacts/451468404) but I cant guarantee there wont be any bugs or unimplemented features.
