### ISSUE TITLE
[FEATURE REQUEST] 1.20.2 Support

### ISSUE THREAD

**Issue by RoonMoonlight** [Intro-Dev/Osmium#42]
**Is your feature request related to a problem? Please describe.**
The mod does not run on 1.20.2 and displays error.

**Describe the solution you'd like**
Update mod to support 1.20.2

**Describe alternatives you've considered**
no.

**Additional context**
no.

**Comment by Intro-Dev** [comment]
A 1.20.2 port is currently in the works and should be out soon.

**Comment by Intro-Dev** [comment]
Port is finished.
