### ISSUE TITLE
[FEATURE REQUEST]Port it to 1.18.1 Forge,Plz!!!

### ISSUE THREAD

**Issue by Hamster-github** [Intro-Dev/Osmium#44]
I very need Osmium 1.18.1 Forge Version.I want to play a 1.18.1 bedwars server.Plz!!!

**Comment by Intro-Dev** [comment]
Unfortunately a port to forge, especially on an older version of minecraft would be very difficult and time consuming. As a solution, you can try to find fabric equivalents for any forge mods you may have, and if possible, update to a newer version of minecraft to get more updated features from your mods.
